export const appIcons = {
  backArrow: require('../../assets/icons/png/backArrow.png'),
  filter: require('../../assets/icons/png/filter.png'),
  plus: require('../../assets/icons/png/plus.png'),
  mobiledata: require('../../assets/icons/png/mobiledata.png'),
  homeIconBg: require('../../assets/icons/png/homeIcons/home_icon_bg.png'),
  createRide: require('../../assets/icons/png/homeIcons/createRide.png'),
  recurringRide: require('../../assets/icons/png/homeIcons/recurringRide.png'),
  cityRide: require('../../assets/icons/png/homeIcons/cityRide.png'),
  noUpcomingRide: require('../../assets/icons/png/no_upcoming_ride.png'),
  cancel: require('../../assets/icons/png/cancel.png'),
  landing_img: require('../../assets/icons/png/landingImg.png'),
  drawerIcon: require('../../assets/icons/png/homeIcons/recurringRide.png'),
  walkthrough_img_one: require('../../assets/icons/png/walkthroughimg1.png'),
  walkthrough_img_two: require('../../assets/icons/png/walkthroughimg2.png'),
  landing_user_img: require('../../assets/icons/png/landingUserImg.png'),
  permission_img: require('../../assets/icons/png/permission.png'),
  share_icon: require('../../assets/icons/png/share.png'),
  spread_goodness: require('../../assets/icons/png/spread_goodness.png'),
  next: require('../../assets/icons/png/next.png'),
  car_icon: require('../../assets/icons/png/driver/driver_recurring_ride.png'),
};
export const appImages = {
  visa: require('../../assets/images/visa.png'),
  leftcar: require('../../assets/images/leftcar.png'),

  user: require('../../assets/images/user.png'),
  seatBlue: require('../../assets/icons/png/seat_blue.png'),
  seatGreen: require('../../assets/icons/png/seat_green.png'),
  calendar: require('../../assets/icons/png/calendar.png'),
  app_logo: require('../../assets/icons/png/app_logo.png'),
  valley: require('../../assets/images/valley.png'),
  inviteImage: require('../../assets/icons/png/invite_prop.png'),
  driver: require('../../assets/icons/png/driver/driver.png'),
};
export const drawerIcons = {
  Favourites: require('../../assets/icons/png/drawerIcons/Favourites.png'),
  invite: require('../../assets/icons/png/drawerIcons/invite.png'),
  logout: require('../../assets/icons/png/drawerIcons/logout.png'),
  my_contribution: require('../../assets/icons/png/drawerIcons/my_contribution.png'),
  my_payment_methods: require('../../assets/icons/png/drawerIcons/my_payment_methods.png'),
  offers: require('../../assets/icons/png/drawerIcons/offers.png'),
  reports: require('../../assets/icons/png/drawerIcons/reports.png'),
  rides_history: require('../../assets/icons/png/drawerIcons/rides_history.png'),
  settings: require('../../assets/icons/png/drawerIcons/settings.png'),
};
